let mapleader=" "
let g:plugDirctory='~/.vim/plugged'

let g:isWindows=0
if(has("win32") || has("win64") || has("win95") || has("win16"))
	let g:isWindows=1
	let g:plugDirctory='$HOMEPATH\vimfiles\plugged'
endif

syntax on

filetype on
filetype indent on
filetype plugin on
filetype plugin indent on

set encoding=utf-8
set t_Co=256

set laststatus=2
set showcmd
set ruler
set wildmenu
set autochdir

set autoindent
set tabstop=4
set shiftwidth=4
set backspace=2
"set expandtab
"set softtabstop=4

set number
set relativenumber
set scrolloff=5
set cursorline
set wrap
set list
set listchars=trail:■,tab:>-

set showmatch
set hlsearch
set incsearch
set ignorecase
set smartcase

noremap H 5h
noremap J 5j
noremap K 5k
noremap L 5l

noremap sh :set nosplitright<CR>:vsplit<CR>
noremap sl :set splitright<CR>:vsplit<CR>
noremap sk :set nosplitbelow<CR>:split<CR>
noremap sl :set splitbelow<CR>:split<CR>
noremap <LEADER>h <C-w>h
noremap <LEADER>j <C-w>j
noremap <LEADER>k <C-w>k
noremap <LEADER>l <C-w>l
noremap <up> :resize +5<CR>
noremap <down> :resize -5<CR>
noremap <left> :vertical resize -5<CR>
noremap <right> :vertical resize +5<CR>

noremap te :tabedit<CR>
noremap tn :tabnext<CR>
noremap tb :tabprevious<CR>

noremap = nzz
noremap - Nzz
noremap <LEADER><CR> :nohlsearch<CR>

if(g:isWindows)
	colorscheme Tomorrow-Night

	source $VIMRUNTIME/delmenu.vim
	source $VIMRUNTIME/menu.vim

	set fileencodings=utf-8,gbk2312,gbk,gb18030,cp936
	set encoding=utf-8
	set langmenu=zh_CN
	let $LANG = 'en_US.UTF-8'

	set guioptions-=T
	set guioptions-=m
	set guioptions-=L
	set guioptions-=r
	set guioptions-=b
	set guioptions-=e

	set guifont=Inconsolata:h16:cANSI

	set clipboard+=unnamed
	set winaltkeys=no
endif

"-----Install Vim-plug
"curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

"-----Install nodejs for coc.nvim
"curl -sL install-node.now.sh/lts | bash

call plug#begin(g:plugDirctory)
	Plug 'scrooloose/nerdtree',{'on':'NERDTreeToggle'}
	Plug 'neoclide/coc.nvim', {'branch': 'release'}
	Plug 'vim-airline/vim-airline'
	Plug 'vim-airline/vim-airline-themes'
	Plug 'machakann/vim-sandwich'
	Plug 'gcmt/wildfire.vim'
call plug#end()

let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'

noremap <F5> :NERDTreeToggle<CR>

"Coc settings
set hidden
set shortmess+=c

let g:coc_global_extensions = ['coc-vimlsp','coc-clangd']

inoremap <silent><expr> <TAB>
	\ pumvisible() ? "\<C-n>" :
	\ <SID>check_back_space() ? "\<TAB>" :
	\ coc#refresh()

inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
	let col = col('.') - 1
	return !col || getline('.')[col - 1] =~# '\s'
endfunction
